### ISSUE TITLE
Error report when run

### ISSUE THREAD

**Issue by Panhaolin2001** [jansel/opentuner#168]

**Comment by Panhaolin2001** [comment]
Traceback (most recent call last):
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./examples/rosenbrock/rosenbrock.py", line 85, in <module>
    Rosenbrock.main(args)
  File "/home/haolin/project/opentuner/opentuner/measurement/interface.py", line 300, in main
    return TuningRunMain(cls(args, *pargs, **kwargs), args).main()
  File "/home/haolin/project/opentuner/opentuner/tuningrunmain.py", line 98, in __init__
    self.engine, self.Session = resultsdb.connect(args.database)
  File "/home/haolin/project/opentuner/opentuner/resultsdb/connect.py", line 45, in connect
    connection = engine.connect()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3276, in connect
    return self._connection_cls(self)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2440, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
    self._dec_overflow()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/haolin/anaconda3/envs/opentuner/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by huangshangmin0415** [comment]
in opentuner/tuningrunmain.py line 90 it makes a strange database path 'sqlite:///opentuner.db/yourhostname.db', so i replace the path by 'sqlite:///opentuner_yourhostname.db' and error disappears. i guess something in the search codes to be done for better results
